# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1647bc8350ce5032a7e070582d1d610ef1fb3afd37f82750142de0af202f7f7bbe6beb4d6d0eaccf443ba8c0442af583f4935f91e580d5f3724a3831aab437f3

test:
  secret_key_base: 842deb665ba2b637624bfbb9fcfc5f1181fd35df697b15dbeaebc42eb2d3b9d9218d7f9a61d1e18202188643d168307ce333fa380f19800360a130216a602718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
